### ISSUE TITLE
Need feature to add more operations

### ISSUE THREAD

**Issue by ghost** [vikesh-raj/jsonlogic#2]
Wondrful package. It works great with our backend. There is an option in json logic package to add more operations to json logic . Check this [link](https://jsonlogic.com/add_operation.html ). It would be great if you could that support too.

**Comment by vikesh-raj** [comment]
Adding custom operators is already supported.

Checkout this [test](https://github.com/vikesh-raj/jsonlogic/blob/master/test/custom_op_test.dart) case.
This implements GCD operator.

**Comment by vikesh-raj** [comment]
Closing the issue, as the question is answered.
